/**
 * Settings Routes
 *
 * Manages app configuration. Reads from / writes to the .env file
 * so settings persist across server restarts.
 */
const express = require('express');
const router = express.Router();
const fs = require('fs');
const path = require('path');

const ENV_PATH = path.join(__dirname, '..', '.env');

function readEnv() {
  if (!fs.existsSync(ENV_PATH)) return {};
  const content = fs.readFileSync(ENV_PATH, 'utf-8');
  const env = {};
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const val = trimmed.slice(eqIdx + 1).trim();
    env[key] = val;
  }
  return env;
}

function writeEnv(envObj) {
  const lines = [
    '# Meta Ads Manager Configuration',
    '# Auto-generated by setup wizard',
    '',
    '# Meta (Facebook) Marketing API',
    `META_APP_ID=${envObj.META_APP_ID || ''}`,
    `META_APP_SECRET=${envObj.META_APP_SECRET || ''}`,
    `META_AD_ACCOUNT_ID=${envObj.META_AD_ACCOUNT_ID || ''}`,
    `META_ACCESS_TOKEN=${envObj.META_ACCESS_TOKEN || ''}`,
    `META_API_VERSION=${envObj.META_API_VERSION || 'v21.0'}`,
    '',
    '# Shopify Store',
    `SHOPIFY_STORE_DOMAIN=${envObj.SHOPIFY_STORE_DOMAIN || ''}`,
    `SHOPIFY_STOREFRONT_TOKEN=${envObj.SHOPIFY_STOREFRONT_TOKEN || ''}`,
    `SHOPIFY_ADMIN_TOKEN=${envObj.SHOPIFY_ADMIN_TOKEN || ''}`,
    '',
    '# Anthropic Claude API',
    `ANTHROPIC_API_KEY=${envObj.ANTHROPIC_API_KEY || ''}`,
    '',
    '# App Configuration',
    `PORT=${envObj.PORT || '3456'}`,
    `SESSION_SECRET=${envObj.SESSION_SECRET || 'change-this-to-a-random-string'}`,
    `APP_URL=${envObj.APP_URL || 'http://localhost:3456'}`,
  ];
  fs.writeFileSync(ENV_PATH, lines.join('\n') + '\n');
}

// Get current settings (masks secrets)
router.get('/', (req, res) => {
  const env = readEnv();
  res.json({
    meta: {
      app_id: env.META_APP_ID || '',
      app_secret: env.META_APP_SECRET ? '***configured***' : '',
      ad_account_id: env.META_AD_ACCOUNT_ID || '',
      access_token: env.META_ACCESS_TOKEN ? '***configured***' : '',
      api_version: env.META_API_VERSION || 'v21.0',
    },
    shopify: {
      store_domain: env.SHOPIFY_STORE_DOMAIN || '',
      storefront_token: env.SHOPIFY_STOREFRONT_TOKEN ? '***configured***' : '',
      admin_token: env.SHOPIFY_ADMIN_TOKEN ? '***configured***' : '',
    },
    claude: {
      api_key: env.ANTHROPIC_API_KEY ? '***configured***' : '',
    },
    app: {
      port: env.PORT || '3456',
      url: env.APP_URL || 'http://localhost:3456',
    },
  });
});

// Update settings
router.post('/', (req, res) => {
  try {
    const existing = readEnv();
    const updates = req.body;

    // Merge, ignoring masked values
    for (const [key, val] of Object.entries(updates)) {
      if (val && val !== '***configured***') {
        existing[key] = val;
        // Also update process.env so changes take effect immediately
        process.env[key] = val;
      }
    }

    writeEnv(existing);
    res.json({ success: true });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Save just Meta settings
router.post('/meta', (req, res) => {
  try {
    const existing = readEnv();
    const { app_id, app_secret, ad_account_id, access_token } = req.body;

    if (app_id) existing.META_APP_ID = app_id;
    if (app_secret) existing.META_APP_SECRET = app_secret;
    if (ad_account_id) existing.META_AD_ACCOUNT_ID = ad_account_id;
    if (access_token) existing.META_ACCESS_TOKEN = access_token;

    writeEnv(existing);

    // Update process.env
    if (app_id) process.env.META_APP_ID = app_id;
    if (app_secret) process.env.META_APP_SECRET = app_secret;
    if (ad_account_id) process.env.META_AD_ACCOUNT_ID = ad_account_id;
    if (access_token) process.env.META_ACCESS_TOKEN = access_token;

    res.json({ success: true });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Save just Shopify settings
router.post('/shopify', (req, res) => {
  try {
    const existing = readEnv();
    const { store_domain, storefront_token, admin_token } = req.body;

    if (store_domain) existing.SHOPIFY_STORE_DOMAIN = store_domain;
    if (storefront_token) existing.SHOPIFY_STOREFRONT_TOKEN = storefront_token;
    if (admin_token) existing.SHOPIFY_ADMIN_TOKEN = admin_token;

    writeEnv(existing);

    if (store_domain) process.env.SHOPIFY_STORE_DOMAIN = store_domain;
    if (storefront_token) process.env.SHOPIFY_STOREFRONT_TOKEN = storefront_token;
    if (admin_token) process.env.SHOPIFY_ADMIN_TOKEN = admin_token;

    res.json({ success: true });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Save just Claude settings
router.post('/claude', (req, res) => {
  try {
    const existing = readEnv();
    const { api_key } = req.body;

    if (api_key) existing.ANTHROPIC_API_KEY = api_key;

    writeEnv(existing);
    if (api_key) process.env.ANTHROPIC_API_KEY = api_key;

    res.json({ success: true });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

module.exports = router;
